sonar.projectKey=Shear.ly
sonar.projectName=Shear.ly
sonar.projectVersion=1.0

sonar.sources=src

sonar.sourceEncoding=UTF-8

sonar.exclusions=node_modules/**,dist/**,postgres/**,src/generated/**

sonar.host.url=http://localhost:9000