
# Local connections
local   all             all                                     trust

# Primary and replica connections
host    all             all             0.0.0.0/0               scram-sha-256
host    replication     replicator      0.0.0.0/0               scram-sha-256